name: project-name

services:
  system:
    hostname: dev
    build:
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
      - home:/home/node
    networks:
      - back-tier
      - front-tier

  # sample-service:
  #   extends:
  #     file: docker-compose.base.yml
  #     service: node-app-base
  #   environment:
  #     - SERVICE_NAME=sample-service
  #   command: npm -w apps/sample-service
  #   networks:
  #     - back-tier
  #     - front-tier

  # redis:
  #   image: redis:8.0
  #   volumes:
  #     - redis:/data
  #   networks:
  #     - back-tier

  # redis-insight:
  #   image: redis/redisinsight:latest
  #   ports:
  #     - 5540:5540
  #   environment:
  #     RI_REDIS_HOST: redis
  #     RI_FILES_LOGGER: false
  #   volumes:
  #     - redisinsight:/db
  #   networks:
  #     - back-tier

  # db:
  #   image: postgres:17
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: secret
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #     - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - back-tier

  # grafana:
  #   image: grafana/otel-lgtm:latest
  #   ports:
  #     - "5000:3000"
  #   environment:
  #     GF_AUTH_ANONYMOUS_ENABLED: "true"
  #     GF_USERS_DEFAULT_THEME: "light"
  #   volumes:
  #     - grafana-data:/data/grafana/data
  #   networks:
  #     - back-tier

volumes:
  home: {}
  # grafana-data: {}
  # postgres: {}
  # redis: {}
  # redisinsight: {}


networks:
  back-tier: {}
  front-tier: {}
