name: generator

services:
  system:
    hostname: dev
    build:
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - home:/home/dev
    networks:
      - back-tier

volumes:
  home: {}

networks:
  back-tier: {}
